# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...&& ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
    # Artifact name
        name: TlsScan # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: f

    - name: Test
      run: go test -v ./...
